export const TICKET_MANAGER_ABI = [
  {
    inputs: [
      { internalType: "address", name: "_platformWallet", type: "address" },
      { internalType: "uint256", name: "_platformFee", type: "uint256" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      { internalType: "string", name: "eventId", type: "string" },
      { internalType: "string", name: "eventName", type: "string" },
      { internalType: "string", name: "venue", type: "string" },
      { internalType: "string", name: "date", type: "string" },
      { internalType: "string", name: "attendeeName", type: "string" },
      { internalType: "string", name: "_tokenURI", type: "string" },
    ],
    name: "purchaseTicket",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "to", type: "address" },
      { internalType: "string", name: "eventId", type: "string" },
      { internalType: "string", name: "eventName", type: "string" },
      { internalType: "string", name: "venue", type: "string" },
      { internalType: "string", name: "date", type: "string" },
      { internalType: "string", name: "attendeeName", type: "string" },
      { internalType: "string", name: "_tokenURI", type: "string" },
    ],
    name: "mintFreeTicket",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "redeemTicket",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "verifyTicket",
    outputs: [
      { internalType: "bool", name: "isValid", type: "bool" },
      { internalType: "string", name: "eventId", type: "string" },
      { internalType: "string", name: "eventName", type: "string" },
      { internalType: "string", name: "attendeeName", type: "string" },
      { internalType: "enum TicketManager.TicketStatus", name: "status", type: "uint8" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "getTicketInfo",
    outputs: [
      {
        components: [
          { internalType: "string", name: "eventId", type: "string" },
          { internalType: "string", name: "eventName", type: "string" },
          { internalType: "string", name: "venue", type: "string" },
          { internalType: "string", name: "date", type: "string" },
          { internalType: "string", name: "attendeeName", type: "string" },
          { internalType: "uint256", name: "pricePaid", type: "uint256" },
          { internalType: "enum TicketManager.TicketStatus", name: "status", type: "uint8" },
          { internalType: "uint256", name: "mintTimestamp", type: "uint256" },
        ],
        internalType: "struct TicketManager.Ticket",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "redeemer", type: "address" },
      { internalType: "bool", name: "authorized", type: "bool" },
    ],
    name: "setAuthorizedRedeemer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_fee", type: "uint256" }],
    name: "setPlatformFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_wallet", type: "address" }],
    name: "setPlatformWallet",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalTickets",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "platformFee",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "platformWallet",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "tokenId", type: "uint256" },
      { indexed: true, internalType: "address", name: "buyer", type: "address" },
      { indexed: false, internalType: "string", name: "eventId", type: "string" },
      { indexed: false, internalType: "string", name: "eventName", type: "string" },
      { indexed: false, internalType: "uint256", name: "pricePaid", type: "uint256" },
    ],
    name: "TicketPurchased",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "tokenId", type: "uint256" },
      { indexed: true, internalType: "address", name: "redeemer", type: "address" },
    ],
    name: "TicketRedeemed",
    type: "event",
  },
] as const
